# NumPy Basics

NumPy (Numerical Python) is a powerful Python library for numerical operations. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them.

To install:
```bash
pip install numpy
```

## What is an ndarray?

The core of NumPy is the `ndarray` (n-dimensional array). It stores elements of the same type and allows efficient numerical computations.

- Items are indexed using zero-based indices.
- All elements share the same data type (`dtype`).
- Arrays can be 1D, 2D, 3D, and more.

<img src="images/array.png" alt="Concept-Alert" style="width:300px; height:200px; margin-bottom:15px;"/>

In [1]:
pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# 1D array from list
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [4]:
# 2D array from list of lists
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]


## Array Properties

In [5]:
print(arr2.shape)    # Shape of array


(2, 2)


In [6]:
print(arr2.ndim)     # Number of dimensions


2


In [7]:
print(arr2.dtype)    # Data type of elements Can be INT, FLOAT, BOOL

int64


In [8]:
#lets create some arrays
my_list = [100, 200, 300]

arr = np.array(my_list)

In [11]:
#print(arr.shape)    # Shape of array
#print(arr.ndim)     # Number of dimensions
print(arr.dtype) 

int64


## Common Array Creation Methods

In [12]:
np.zeros((2, 3))
#np.zeros((2, 3), dtype=int)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Indexing and Slicing

In [17]:
arr = np.array([10, 20, 30, 40, 50])


In [19]:
#print(arr[1])
print(arr[1:4])

[20 30 40]


In [20]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])


In [21]:
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
print(matrix[1]) #if you give a single index for a 2d matrix you are grabbing rows

[3 4]


In [24]:
print(matrix[1][0])

3


In [26]:
print(matrix[2][1])

6


In [25]:
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


## Basic Operations

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
#print(a + b) #vectorized addition, but this will fail if arrays are if diff lenght
#print(a * b)
print(a ** 2)

[1 4 9]


In [28]:
#this gives an error when lengths dont match
a = np.array([1, 2, 3])
b = np.array([4, 5])
print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [31]:
print(np.mean(a))


2.0


In [32]:
print(np.sum(a))


6


In [33]:
print(np.max(a))

3


## SOME BUILT IN FUNCTIONS 

In [ ]:
# linspace()
# Creates evenly spaced numbers over a range.
# You control how many values you want.

# linspace(start, stop, num=50, endpoint=True, retstep=False) -->

In [34]:
np.linspace(0, 100, 10)  # 10 values from 0 to 100... 9 EQUAL GAPS


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [35]:
#Create an array of the given shape and populate it with random samples from a uniform distribution
np.random.rand(3, 4)

array([[0.32784647, 0.09567122, 0.21359232, 0.16963192],
       [0.88180371, 0.32252144, 0.9996547 , 0.33228283],
       [0.2831269 , 0.8044929 , 0.37365988, 0.5886327 ]])

In [36]:
# 10 random integers between 3 (inclusive) to 90 (exclusive)

np.random.randint(3, 90, 10)

array([49, 52, 53, 79, 83, 76, 61, 43, 13, 35])

In [37]:
# Creates evenly spaced values.
# Works like Python’s range() but returns a NumPy array.
# arange([start,] stop[, step,][, dtype])
np.arange(0, 10, 3)  


array([0, 3, 6, 9])

## Summary

NumPy is essential for data analysis, machine learning, and scientific computing in Python. Mastering `ndarray` operations is the first step in becoming proficient with data in Python.